# This workflow will build and publish a WinUI 3 unpackaged desktop application
# built on .NET.

name: Build And Release JASM Self Contained

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Test
      run: dotnet test ${{ github.workspace }}\src

    - name: Build, publish and zip the app
      run: python ${{ github.workspace }}\Build\Release.py SelfContained ExcludeElevator
      shell: cmd

    # Upload the app
    - name: Upload JASM Self Contained
      uses: actions/upload-artifact@v3
      with:
        name: JASM Self Contained
        path: ${{ github.workspace }}\\${{ env.zipFile }}
        
